apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis
  template:
    metadata:
      labels:
        type: redis
    spec:
      containers:
      - name: redis
        image: gcr.io/ismael-lab/redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service	
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379